"""Public API for collective-sim."""

from .predictor import predict_collective_time
from .scenario_profiles import (
    cluster_a100_8gpu,
    cluster_a800_8gpu,
    cluster_h100_8gpu,
    cluster_h800_8gpu,
    get_scenario_profile_builder,
    intra_a100_nvlink,
    intra_a800_nvlink,
    intra_h100_nvlink,
    intra_h800_nvlink,
    list_scenario_profiles,
    register_scenario_profile,
    scenario_template,
    scenario_profile_a100_fattree,
    scenario_profile_a100_rail,
    scenario_profile_a800_fattree,
    scenario_profile_a800_rail,
    scenario_profile_h100_fattree,
    scenario_profile_h100_rail,
    scenario_profile_h800_fattree,
    scenario_profile_h800_rail,
    topology_fat_tree,
    topology_rail_optimized,
)
from .schema import Scenario

__all__ = [
    "predict_collective_time",
    "Scenario",
    "cluster_a100_8gpu",
    "cluster_a800_8gpu",
    "cluster_h100_8gpu",
    "cluster_h800_8gpu",
    "scenario_profile_a100_fattree",
    "scenario_profile_a100_rail",
    "scenario_profile_a800_fattree",
    "scenario_profile_a800_rail",
    "scenario_profile_h100_fattree",
    "scenario_profile_h100_rail",
    "scenario_profile_h800_fattree",
    "scenario_profile_h800_rail",
    "intra_a100_nvlink",
    "intra_a800_nvlink",
    "intra_h100_nvlink",
    "intra_h800_nvlink",
    "topology_rail_optimized",
    "topology_fat_tree",
    "scenario_template",
    "list_scenario_profiles",
    "get_scenario_profile_builder",
    "register_scenario_profile",
]
